name: Publishing the metanorma/metanorma image

on:
  push:
    tags:
    - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        make build
        make test

    - name: Build the Docker image
      run: |
        make bsp-metanorma latest-tp-metanorma
